name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - name: Compile and Package
        run: mvn -V -B package -DskipTests
      - name: Install Package
        run: mvn -V -B install -DskipTests
      - name: Test
        run: mvn -V -B test
